runtime: go
api_version: go1

handlers:
# [START static_handlers]
# If the path is /static, find file in static directory
- url: /static
  static_dir: static
# [END static_handlers]

# All URLs are handled by the Go application script
- url: /.*
  script: _go_app